#ifdef __WAND__
target[name[gmdrumkit.o] type[object]]
#endif

#include "gmdrumkit.h"

const char* MIDIConstants::GmDrumkit::PERCUSSION_NAMES[129]=
	{
	"High resonance value impulse response",
	"Slap",
	"Scratch push",
	"Scratch pull",
	"Drumsticks",
	"Square click",
	"Metronome click",
	"Metronome bell",
	"Bass drum 2",
	"Bass drum 2",
	"RIMSHOT",
	"Snare drum 1",
	"Hand clap",
	"Snare drum 2",
	"Low floor tom",
	"Closed hi-hat",
	"High floor tom",
	"Pedal hi-hat",
	"Low tom",
	"Open hi-hat",
	"Low mid tom",
	"High mid tom",
	"Crash cymbal 1",
	"High tom",
	"Ride cymbal 1",
	"Chinese cymbal",
	"Ride bell",
	"Tambourine",
	"Splash cymbal",
	"Cowbell",
	"Crash cymbal 2",
	"Vibraslap",
	"Ride cymbal 2",
	"High bongo",
	"Low bongo",
	"Muted high conga",
	"Open high conga",
	"Low conga",
	"High timbale",
	"Low timbale",
	"High agogô",
	"Low agogô",
	"Cabasa",
	"Maracas",
	"Short whistle",
	"Long whistle",
	"Short güiro",
	"Long güiro",
	"Claves",
	"High woodblock",
	"Low woodblock",
	"Muted cuíca",
	"Open cuíca",
	"Muted triangle",
	"Open triangle",
	"Shaker",
	"Jingle bell",
	"Belltree",
	"Castanets",
	"Muted surdo",
	"Open surdo",
	"Applause",
	"Cathedral applause",
	nullptr
	};
