#ifdef __WAND__
target[name[gmprograms.o] type[object]]
#endif

#include "gmprograms.h"

const char* MIDIConstants::GmPrograms::PROGRAM_NAMES[129]=
	{
	"Grand piano",
	"Bright piano",
	"Electric grand piano",
	"Honky-Tonk (Ragtime) piano",
	"Electric piano 1",
	"Electric piano 2",
	"Harpsichord",
	"Clavinet",
	"Celesta",
	"Glockenspiel",
	"Music box",
	"Vibraphone",
	"Marimba",
	"Xylophone",
	"Tubular bell",
	"Dulcimer",
	"Drawbar organ",
	"Percussive drawbar organ",
	"Rock (rotary) organ",
	"Church organ",
	"Reed organ",
	"Accordion",
	"Harmonica",
	"Tango accordion",
	"Nylon stringed guitar",
	"Steel stringed guitar",
	"Electric guitar (Jazz)",
	"Electric guitar (Clean)",
	"Electric guitar (Muted)",
	"Electric guitar (Overdrive)",
	"Electric guitar (Distorted)",
	"Electric guitar harmonics",
	"Acoustic bass",
	"Electric bass (Fingered)",
	"Electric bass (Picked)",
	"Electric bass (Fretless)",
	"Electric bass (Slapping 1)",
	"Electric bass (Slapping 2)",
	"Bass synthesizer 1",
	"Bass synthesizer 1",
	"Violin",
	"Viola",
	"Cello",
	"Contrabass",
	"Tremolo strings",
	"Pizzicato strings",
	"Harp",
	"Timpani",
	"Strings 1",
	"Strings 2",
	"String synthesizer",
	"String synthesizer",
	"Choir aah",
	"Choir ooh",
	"Choir synthesizer",
	"Orchestra hit",
	"Trumpet",
	"Trombone",
	"Tuba",
	"Muted trumpet",
	"French horn",
	"Brass section",
	"Brass synthesizer",
	"Brass synthesizer",
	"Soprano saxophone",
	"Alto saxophone",
	"Tenor saxophone",
	"Baritone saxophone",
	"Baritone saxophone",
	"English horn",
	"Bassoon",
	"Clarinet",
	"Piccolo flute",
	"Flute",
	"Recorder",
	"Pan flute",
	"Blown bottle",
	"Shakuhachi",
	"Tin whistle",
	"Ocarina",
	"Lead synthesizer (Square)",
	"Lead synthesizer (Sawtooth)",
	"Lead synthesizer (Calliope)",
	"Lead synthesizer (Chiff)",
	"Lead synthesizer (Charang)",
	"Lead synthesizer (Voice)",
	"Lead synthesizer (Fiths)",
	"Lead synthesizer (Bass+Lead)",
	"Pad synthesizer (New Age)",
	"Pad synthesizer (Polysynth)",
	"Pad synthesizer (Choir)",
	"Pad synthesizer (Bowd)",
	"Pad synthesizer (Metallic)",
	"Pad synthesizer (Halo)",
	"Pad synthesizer (Sweep)",
	"Fx synthesizer (Rain)",
	"Fx synthesizer (Soundtrack)",
	"Fx synthesizer (Crystal)",
	"Fx synthesizer (Atmosphere)",
	"Fx synthesizer (Brightness)",
	"Fx synthesizer (Goblins)",
	"Fx synthesizer (Echoes)",
	"Fx synthesizer (Sci-fi)",
	"Sitar",
	"Banjo",
	"Shamisen",
	"Koto",
	"Kalimba",
	"Bagpipe",
	"Fiddle",
	"Shanai",
	"Tinkle bell",
	"Agogo",
	"Steel drums",
	"Woodblocks",
	"Taiko drums",
	"Melodic toms",
	"Drum synthesizer",
	"Reversed cymbal",
	"Guitar fret noise",
	"Breath noise",
	"Seashore",
	"Bird tweet",
	"Telephone",
	"Helicopter",
	"Applause",
	"Gunshot",
	nullptr
	};
